---
ansible_connection: network_cli
ansible_network_os: ios
ansible_user: cisco
ansible_password: cisco
ansible_become: yes
ansible_become_method: enable
ansible_become_pass: cisco

#All devices params
domain_name: cisco
username: cisco
password: cisco
dmvpn_spoke: 0
dmvpn_hub: 0
